name: Profile 3D Contrib
permissions:
  contents: write
on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: saaedimam
          SETTINGS_JSON: |
            {"theme":"night_rainbow","hours":24}
      - name: Commit 3D graph
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet && echo "no changes" || git commit -m "chore: update 3D contribution graph"
          git push
