name: Update Profile
on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README timestamp
        run: |
          # Add timestamp to show last update
          echo "<!-- Last updated: $(date) -->" >> README.md
          
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "🔄 Auto-update profile stats" || echo "No changes"
          git push
